//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alert.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert_subscriber
    {
        public int id { get; set; }
        public Nullable<byte> member_type { get; set; }
        public string member { get; set; }
        public string os_type { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<byte> isdelete { get; set; }
        public Nullable<int> ids { get; set; }
        public Nullable<long> idkey { get; set; }
    }
}
