//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alert.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alert_group> alert_group { get; set; }
        public virtual DbSet<alert_menu> alert_menu { get; set; }
        public virtual DbSet<alert_permission> alert_permission { get; set; }
        public virtual DbSet<alert_subscriber> alert_subscriber { get; set; }
        public virtual DbSet<alert_user> alert_user { get; set; }
        public virtual DbSet<alert_config> alert_config { get; set; }
        public virtual DbSet<alert_applink> alert_applink { get; set; }
        public virtual DbSet<alert_logfile> alert_logfile { get; set; }
        public virtual DbSet<alert_country> alert_country { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<alert_member> alert_member { get; set; }
    }
}
