//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alert.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert_permission
    {
        public int id { get; set; }
        public Nullable<int> menuid { get; set; }
        public string permission { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
        public string userupdate { get; set; }
    }
}
