//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alert.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert_member
    {
        public int id { get; set; }
        public string name_on_card { get; set; }
        public string card_number { get; set; }
        public string cvv { get; set; }
        public string password { get; set; }
        public string country { get; set; }
        public string zip_code { get; set; }
        public Nullable<byte> isstatus { get; set; }
        public Nullable<byte> istrial { get; set; }
        public Nullable<byte> ischarge { get; set; }
        public string accounts { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public string idkey { get; set; }
        public Nullable<byte> isdelete { get; set; }
        public string date_create { get; set; }
        public string expdate { get; set; }
        public string profileid { get; set; }
        public Nullable<System.DateTime> datecancel { get; set; }
        public string pnref_check { get; set; }
        public string authcode_check { get; set; }
        public string pnref_profile { get; set; }
        public string authcode_profile { get; set; }
        public string trxpnref_profile { get; set; }
        public Nullable<System.DateTime> dateactive { get; set; }
        public string pnref_cancel { get; set; }
    }
}
